name: nuxtexample

services:
  web:
    image: nuxtexample/web:${TAG:-prod}
    build:
      context: .
      dockerfile: src/web/Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider --tries=1 --no-verbose http://localhost:3000/ || exit 1" ]
      interval: 5s
      retries: 10
      start_period: 15s
      timeout: 5s
    networks:
      - web-network
    deploy:
      replicas: 3

  nginx:
    image: nginx:1.27
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:80/health || exit 1" ]
      interval: 5s
      retries: 10
      start_period: 15s
      timeout: 5s
    volumes:
      - ./src/web/nginx.conf:/etc/nginx/nginx.conf
      - ./src/web/mime.types:/etc/nginx/mime.types
    depends_on:
      web:
        condition: service_healthy
    networks:
      - web-network
    ports:
      - "80:80"

networks:
  web-network:
    driver: bridge
